spring.application.name=healverse


# PostgreSQL DB Configuration
spring.datasource.url=jdbc:postgresql://ep-quiet-cherry-a1lwxpfa-pooler.ap-southeast-1.aws.neon.tech/SM_start_mate?user=SM_start_mate_owner&password=npg_fS3CmrsEie6K&sslmode=require&channelBinding=require
spring.datasource.username=SM_start_mate_owner
spring.datasource.password=npg_fS3CmrsEie6K

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server
server.port=8080

# Spring Security
spring.security.user.name=srikar
spring.security.user.password=123
server.servlet.session.cookie.same-site=strict