package com.bytehealers.healverse.service;

import com.bytehealers.healverse.dto.request.LogWaterRequest;
import com.bytehealers.healverse.dto.request.QuickWaterLogRequest;
import com.bytehealers.healverse.model.User;
import com.bytehealers.healverse.model.WaterLog;
import com.bytehealers.healverse.repo.UserRepository;
import com.bytehealers.healverse.repo.WaterLogRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.List;
import java.util.Optional;

@Service
public class WaterLoggingService {

    @Autowired
    private WaterLogRepository waterLogRepository;

    @Autowired
    private NutritionSyncService nutritionSyncService;

    @Autowired
    private UserRepository userRepository;

    public WaterLog logWater(LogWaterRequest request, Long userId) {
        User user = getUserOrThrow(userId); // 🔥 Fetch the user

        WaterLog waterLog = new WaterLog(
                null, // ID (autogenerated)
                user,
                request.getAmountMl(),
                request.getLoggedAt() != null ? request.getLoggedAt() : LocalDateTime.now(),
                null // createdAt (set by @PrePersist)
        );

        WaterLog savedLog = waterLogRepository.save(waterLog);

        nutritionSyncService.syncAfterWaterLog(userId, savedLog.getLoggedAt());

        return savedLog;
    }

    public WaterLog logQuickWater(QuickWaterLogRequest request, Long userId) {
        User user = getUserOrThrow(userId);

        BigDecimal amount = new BigDecimal(request.getPreset().getMilliliters());

        WaterLog waterLog = new WaterLog(
                null,
                user,
                amount,
                request.getLoggedAt() != null ? request.getLoggedAt() : LocalDateTime.now(),
                null
        );

        WaterLog savedLog = waterLogRepository.save(waterLog);

        nutritionSyncService.syncAfterWaterLog(userId, savedLog.getLoggedAt());

        return savedLog;
    }

    public List<WaterLog> getTodaysWaterLogs(Long userId) {
        return waterLogRepository.findTodaysWaterLogs(userId);
    }

    public BigDecimal getTotalWaterIntakeToday(Long userId) {
        return waterLogRepository.findTotalWaterIntakeToday(userId);
    }

    public List<WaterLog> getWaterLogsByDateRange(Long userId, LocalDate startDate, LocalDate endDate) {
        LocalDateTime startDateTime = startDate.atStartOfDay();
        LocalDateTime endDateTime = endDate.atTime(LocalTime.MAX);
        return waterLogRepository.findByUserIdAndLoggedAtBetween(userId, startDateTime, endDateTime);
    }

    public boolean deleteWaterLog(Long waterLogId, Long userId) {
        Optional<WaterLog> existingLog = waterLogRepository.findById(waterLogId);

        if (existingLog.isEmpty()) {
            return false;
        }

        WaterLog waterLog = existingLog.get();

        if (!waterLog.getUser().getId().equals(userId)) {
            throw new RuntimeException("Unauthorized access");
        }

        LocalDateTime loggedAt = waterLog.getLoggedAt();
        waterLogRepository.delete(waterLog);

        nutritionSyncService.syncAfterWaterLog(userId, loggedAt);

        return true;
    }


    private User getUserOrThrow(Long userId) {
        return userRepository.findById(userId)
                .orElseThrow(() -> new RuntimeException("User not found for ID: " + userId));
    }
}
